### ISSUE TITLE
Remove Retweets doesn't work!

### ISSUE THREAD

**Issue by JohnDoeIsBack** [nikolaydubina/twitter-remover#2]
It just keeps on scrolling instead of removing the RTs.

**Comment by nikolaydubina** [comment]
it was working before. I guess twitter changed again something. I will fix later on if I have time

**Comment by im-PJs** [comment]
`setInterval(() => {
    for (const d of document.querySelectorAll('button[data-testid="unretweet"]')) {
        d.click();
        for (const c of document.querySelectorAll('div[data-testid="unretweetConfirm"]')) {
            c.click();
        }
    }
    window.scrollTo(0, document.body.scrollHeight);
}, 1000);
`

Fixing it to this worked for me

**Comment by nikolaydubina** [comment]
@im-PJs do you mind opening a PR? for attribution

**Comment by UmishBaluni** [comment]
Not working....It just keeps on scrolling instead of removing the RTs.

**Comment by nikolaydubina** [comment]
ok @woj-tek @UmishBaluni I fixed it. just worked for me. try again.

if does not work, try to fix it, and feel free to raise a PR
